<?php

declare(strict_types=1);

// Managed by bootstrap. PHP-CS-Fixer with the @Symfony ruleset (§11.7).
//
// PHP-CS-Fixer owns code style here, including `declare(strict_types=1);`
// placement. We enforce strict types right after `<?php` (no blank line in
// between) so it agrees with Rector's declare handling. Otherwise the cs and
// rector dry-run gates fight over that one line.

$finder = (new PhpCsFixer\Finder())
    ->in(__DIR__)
    ->exclude(['var', 'vendor', 'public/bundles'])
    // config/reference.php is regenerated by Symfony Flex on every composer
    // operation without declare(strict_types=1): leaving it managed would make
    // php-cs-fixer loop against Flex.
    ->notPath('config/reference.php')
    ->append([__FILE__]);

return (new PhpCsFixer\Config())
    ->setRiskyAllowed(true)
    ->setRules([
        '@Symfony' => true,
        '@Symfony:risky' => true,
        'declare_strict_types' => true,
        'blank_line_after_opening_tag' => false,
    ])
    ->setFinder($finder);
